name = "freshink"
main = "worker/index.js"
compatibility_date = "2026-05-21"

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
# Optional default server endpoints (configure on cloudflare dashboard or override in headers)
FRESHRSS_URL = ""
# FRESHRSS_USER = ""
# FRESHRSS_PASSWORD = ""
